#!/bin/bash
set -e
source $( cd "$( dirname "$0" )" && pwd )/constants.env

cd $PY_LIB_ROOT
for dir in `ls .`
do
    if [ -d $dir ]; then
        PYTHONPATH=$PYTHONPATH:$PY_LIB_ROOT/$dir
    fi
done
export PYTHONPATH=$PYTHONPATH:.

python "$@"
